import React, { useState } from 'react';
import {
  Activity,
  AlertOctagon,
  CheckCircle2,
  CalendarClock,
  ArrowUpRight,
  TrendingDown,
  Filter,
  Eye,
  MapPin,
  Clock,
  Phone,
  ChevronRight,
  AlertTriangle,
} from 'lucide-react';
import { CaseClinicalDetails } from '../data/paravetMockData';
import { HealthStatus } from '../../types';
import champaCowPhoto from '../../assets/images/champa_cow_portrait_1790444600765.jpg';

interface DashboardHomeProps {
  referrals: CaseClinicalDetails[];
  onSelectReferral: (referral: CaseClinicalDetails) => void;
  onNavigateToTab: (tab: any) => void;
}

export const DashboardHome: React.FC<DashboardHomeProps> = ({
  referrals,
  onSelectReferral,
  onNavigateToTab,
}) => {
  const [filterRisk, setFilterRisk] = useState<'all' | 'Urgent' | 'Veterinary Review'>('all');

  const urgentCount = referrals.filter((r) => r.riskLevel === 'Urgent').length;
  const reviewCount = referrals.filter((r) => r.riskLevel === 'Veterinary Review').length;
  const activeCasesCount = referrals.length + 11; // 14 total active cases in Karnal block

  const filteredReferrals = referrals.filter((r) => {
    if (filterRisk === 'all') return true;
    return r.riskLevel === filterRisk;
  });

  const getRiskBadge = (risk: HealthStatus) => {
    switch (risk) {
      case 'Urgent':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-red-100 text-red-800 border border-red-200">
            <span className="w-1.5 h-1.5 rounded-full bg-red-600 animate-pulse" />
            Urgent
          </span>
        );
      case 'Veterinary Review':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-200">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-600" />
            Veterinary Review
          </span>
        );
      case 'Attention':
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-yellow-100 text-yellow-800 border border-yellow-200">
            <span className="w-1.5 h-1.5 rounded-full bg-yellow-600" />
            Attention
          </span>
        );
      case 'Healthy':
      default:
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-200">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-600" />
            Healthy
          </span>
        );
    }
  };

  return (
    <div className="space-y-6">
      {/* Welcome Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-[16px] bg-gradient-to-r from-[#166534] to-[#14532D] text-white shadow-sm">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold tracking-tight">Karnal Block Clinical Triage Console</h1>
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-400/20 text-emerald-200 border border-emerald-400/30">
              Live Network
            </span>
          </div>
          <p className="text-xs text-emerald-100/90 mt-1 max-w-2xl leading-relaxed">
            Automatic veterinary referrals generated by AARVI voice triage from registered dairy farmers across Karnal, Kachhwa, and Nilokheri blocks.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <button
            type="button"
            onClick={() => onNavigateToTab('appointments')}
            className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-white border border-white/20 text-xs font-semibold backdrop-blur-xs transition-all cursor-pointer"
          >
            Today's Dispatch (4)
          </button>
          <button
            type="button"
            onClick={() => onNavigateToTab('referrals')}
            className="px-3.5 py-2 rounded-xl bg-white text-[#166534] hover:bg-stone-50 text-xs font-bold shadow-xs transition-all cursor-pointer"
          >
            Review All Queue
          </button>
        </div>
      </div>

      {/* Top 4 Metrics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Metric 1: Active Cases */}
        <div className="p-4 rounded-[16px] bg-white border border-stone-200/90 shadow-xs hover:border-[#166534]/40 transition-all">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-stone-500 uppercase tracking-wider">
              Active Cases
            </span>
            <div className="w-8 h-8 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center">
              <Activity className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-2.5 flex items-baseline gap-2">
            <span className="text-2xl font-black text-stone-900">{activeCasesCount}</span>
            <span className="text-[11px] font-semibold text-emerald-700 flex items-center">
              +2 today
            </span>
          </div>
          <p className="text-[11px] text-stone-500 mt-1 truncate">
            {reviewCount} review cases under observation
          </p>
        </div>

        {/* Metric 2: Urgent Referrals */}
        <div className="p-4 rounded-[16px] bg-white border border-red-200 shadow-xs hover:border-red-300 transition-all bg-gradient-to-br from-white to-red-50/30">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-red-700 uppercase tracking-wider">
              Urgent Referrals
            </span>
            <div className="w-8 h-8 rounded-xl bg-red-100 text-red-700 flex items-center justify-center">
              <AlertOctagon className="w-4 h-4 animate-pulse" />
            </div>
          </div>
          <div className="mt-2.5 flex items-baseline gap-2">
            <span className="text-2xl font-black text-red-700">{urgentCount}</span>
            <span className="text-[11px] font-bold text-red-600 bg-red-100 px-1.5 py-0.5 rounded-sm">
              Immediate Action
            </span>
          </div>
          <p className="text-[11px] text-red-600 font-medium mt-1 truncate">
            FMD & hyperthermia ambulance dispatched
          </p>
        </div>

        {/* Metric 3: Healthy Animals */}
        <div className="p-4 rounded-[16px] bg-white border border-stone-200/90 shadow-xs hover:border-[#166534]/40 transition-all">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-stone-500 uppercase tracking-wider">
              Healthy Animals
            </span>
            <div className="w-8 h-8 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center">
              <CheckCircle2 className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-2.5 flex items-baseline gap-2">
            <span className="text-2xl font-black text-stone-900">182</span>
            <span className="text-[11px] font-bold text-emerald-700 bg-emerald-50 px-1.5 py-0.5 rounded-sm">
              94.2% Rate
            </span>
          </div>
          <p className="text-[11px] text-stone-500 mt-1 truncate">
            Baseline yield maintained across block
          </p>
        </div>

        {/* Metric 4: Today's Visits */}
        <div className="p-4 rounded-[16px] bg-white border border-stone-200/90 shadow-xs hover:border-[#166534]/40 transition-all">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-stone-500 uppercase tracking-wider">
              Today's Visits
            </span>
            <div className="w-8 h-8 rounded-xl bg-[#166534]/10 text-[#166534] flex items-center justify-center">
              <CalendarClock className="w-4 h-4" />
            </div>
          </div>
          <div className="mt-2.5 flex items-baseline gap-2">
            <span className="text-2xl font-black text-stone-900">4</span>
            <span className="text-[11px] font-semibold text-stone-500">
              2 Completed
            </span>
          </div>
          <p className="text-[11px] text-stone-500 mt-1 truncate">
            Ambulance Unit 2 en route Sector 14
          </p>
        </div>
      </div>

      {/* Below Metrics: Recent Referrals From Farmers */}
      <div className="p-5 rounded-[16px] bg-white border border-stone-200/90 shadow-xs">
        {/* Section Header with Filter Tabs */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-stone-100">
          <div>
            <h2 className="text-base font-bold text-stone-900 tracking-tight">
              Recent Referrals from Farmers
            </h2>
            <p className="text-xs text-stone-500 mt-0.5">
              Live case files automatically generated by AARVI during clinical voice screening
            </p>
          </div>

          {/* Filter Pills */}
          <div className="flex items-center gap-1.5 self-start sm:self-auto bg-stone-100 p-1 rounded-xl">
            <button
              type="button"
              onClick={() => setFilterRisk('all')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                filterRisk === 'all'
                  ? 'bg-white text-stone-900 shadow-2xs font-bold'
                  : 'text-stone-600 hover:text-stone-900'
              }`}
            >
              All ({referrals.length})
            </button>
            <button
              type="button"
              onClick={() => setFilterRisk('Urgent')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                filterRisk === 'Urgent'
                  ? 'bg-red-600 text-white shadow-2xs font-bold'
                  : 'text-stone-600 hover:text-red-700'
              }`}
            >
              Urgent ({urgentCount})
            </button>
            <button
              type="button"
              onClick={() => setFilterRisk('Veterinary Review')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                filterRisk === 'Veterinary Review'
                  ? 'bg-amber-600 text-white shadow-2xs font-bold'
                  : 'text-stone-600 hover:text-amber-800'
              }`}
            >
              Review ({reviewCount})
            </button>
          </div>
        </div>

        {/* Referrals Cards Grid / List */}
        <div className="divide-y divide-stone-100 mt-2">
          {filteredReferrals.length === 0 ? (
            <div className="py-12 text-center text-stone-500 text-xs">
              No referrals match the selected filter.
            </div>
          ) : (
            filteredReferrals.map((referral) => (
              <div
                key={referral.id}
                onClick={() => onSelectReferral(referral)}
                className="py-4 hover:bg-[#F8FAF7] rounded-xl px-3 transition-colors cursor-pointer flex flex-col md:flex-row md:items-center justify-between gap-4 group"
              >
                {/* Cow Image & Name & Details */}
                <div className="flex items-center gap-3.5 min-w-0">
                  <div className="relative w-14 h-14 rounded-xl overflow-hidden shrink-0 border border-stone-200 shadow-2xs">
                    <img
                      src={referral.photoUrl}
                      alt={referral.cattleName}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                      onError={(e) => {
                        e.currentTarget.onerror = null;
                        e.currentTarget.src = champaCowPhoto;
                      }}
                    />
                    {referral.riskLevel === 'Urgent' && (
                      <span className="absolute top-1 right-1 w-2.5 h-2.5 rounded-full bg-red-500 ring-2 ring-white animate-pulse" />
                    )}
                  </div>

                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <h3 className="text-sm font-bold text-stone-900 group-hover:text-[#166534] transition-colors truncate">
                        {referral.cattleName}
                      </h3>
                      <span className="text-[11px] font-mono px-1.5 py-0.5 rounded-md bg-stone-100 text-stone-600 font-medium">
                        {referral.tag}
                      </span>
                      <span className="text-xs text-stone-400">•</span>
                      <span className="text-xs text-stone-600 font-medium">{referral.breed}</span>
                    </div>

                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-stone-500 mt-1">
                      <span className="font-semibold text-stone-700">
                        Farmer: {referral.farmerName}
                      </span>
                      <span className="flex items-center gap-1 text-stone-500">
                        <MapPin className="w-3 h-3 text-stone-400" />
                        {referral.location}
                      </span>
                      <span className="flex items-center gap-1 text-stone-400">
                        <Clock className="w-3 h-3" />
                        {referral.createdAt}
                      </span>
                    </div>

                    {/* Complaint snippet */}
                    <p className="text-xs text-stone-600 font-normal mt-1.5 line-clamp-1">
                      <span className="font-semibold text-stone-800">Primary Complaint: </span>
                      {referral.chiefComplaints[0]}
                    </p>
                  </div>
                </div>

                {/* Right: Risk Badge & View Case Button */}
                <div className="flex items-center justify-between md:justify-end gap-3 shrink-0">
                  <div>{getRiskBadge(referral.riskLevel)}</div>

                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      onSelectReferral(referral);
                    }}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white group-hover:bg-[#166534] text-stone-700 group-hover:text-white border border-stone-200 group-hover:border-[#166534] text-xs font-semibold shadow-2xs transition-all cursor-pointer"
                  >
                    <span>View Case File</span>
                    <ChevronRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};
